services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
    ports:
      - "8080:80"
    depends_on:
      php-fpm:
        condition: service_healthy
      mysql:
        condition: service_healthy

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy

  php-cli:
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - COMPOSER_MEMORY_LIMIT=-1
    tty: true
    working_dir: /var/www
    user: "${UID:-1000}:${GID:-1000}"

  mysql:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=my_db
    ports:
      - "33061:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=password
      - UPLOAD_LIMIT=64M
    ports:
      - 8081:80
    depends_on:
      mysql:
        condition: service_healthy

  node:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true

volumes:
  database: