#!/usr/bin/env php
<?php

use App\Core\Facades\Command;

require_once __DIR__ . '/src/app/Core/Bootstrap/bootstrap.php';


$command = strtolower($argv[1] ?? null);
$name = $argv[2] ?? null;
$type = $argv[3] ?? null;

switch ($command) {
    case 'serve':
        Command::serve();
        break;

    case 'make:controller':
        echo Command::makeController($name, $type);
        break;

    case 'make:model':
        echo Command::makeModel($name);
        break;

    case null:
        echo "Введите команду🤒.\n";
        break;

    default:
        echo "Неизвестная команда: $command\n";
        echo "Введите php blaze --help для получения списка команд\n";
        break;
}